### ISSUE TITLE
PDF's in ..\..\assets\presentation are damaged

### ISSUE THREAD

**Issue by RonaldTester** [OWASP/www-project-api-security#4]
I'll try to open the pdf's, but get the message that the files can't be opened because they are damaged.

**Comment by nikitakoselev** [comment]
all 3 PDFs in https://github.com/OWASP/www-project-api-security/tree/master/assets/presentations work for me:
![image](https://user-images.githubusercontent.com/6383738/215346193-86c3f0ca-d44a-474b-9aad-72589983b506.png)
![image](https://user-images.githubusercontent.com/6383738/215346205-41afd3ff-8de6-4dea-ae5f-84bb9be6947b.png)
![image](https://user-images.githubusercontent.com/6383738/215346211-b83a17a0-02b2-46e5-8423-3b93ecb0dae5.png)

Doens't look to be an issue - please consider closing the ticket.
