### ISSUE TITLE
typo in project description

### ISSUE THREAD

**Issue by janibashamd** [OWASP/www-project-api-security#6]
In About section "repository" typo mapped to "respository"

**Comment by ErezYalon** [comment]
Thanks, @janibashamd, would you like to open a PR?

**Comment by janibashamd** [comment]
Sure please assign it to me with permissions needed for pushing...

**Comment by PauloASilva** [comment]
Hi @janibashamd,
No special permissions are required. 

I believe you'll be able to do it using GitHub UI, nevertheless the underlying workflow should be:

1. Fork this repository
2. Do the required changes in your fork
3. Commit your changes (in your fork)
4. Open a PR from your fork into this repository `master` branch.

Cheers,
Paulo A. Silva

**Comment by janibashamd** [comment]
@PauloASilva as this is not related to code, i don't see the option to raise a PR as below:
![image](https://user-images.githubusercontent.com/6093830/229849983-01bf307b-488e-4f2d-b8d1-a576f3505005.png)


So please remove 's' from project description which should be fine from my end !

**Comment by PauloASilva** [comment]
@janibashamd 
can you please highlight in the screenshot which `s` should be removed: I am a bit lost.

Cheers,
Paulo A. Silva

**Comment by janibashamd** [comment]
FYI:
![image](https://user-images.githubusercontent.com/6093830/230713927-54413837-3cae-42f8-af4e-5c09db83bbc8.png)

**Comment by PauloASilva** [comment]
@janibashamd: thanks for pointing that out!
