### ISSUE TITLE
Persian Translation

### ISSUE THREAD

**Issue by This-is-Neo** [OWASP/www-project-api-security#7]
Hello!
I volunteer for translating the API TOP10 2023 to Farsi/Persian & would want to know your opinion on this matter.

**Comment by ErezYalon** [comment]
Hi there, this is the repo for the page on the OWASP website.
The repo of the Top10 project is here: https://github.com/OWASP/API-Security
Here is how to contribute: https://github.com/OWASP/API-Security/blob/master/CONTRIBUTING.md
A good place to start is previous translation issues (including Farsi): https://github.com/OWASP/API-Security/issues?q=label%3Atranslation
